import type { Metadata } from "next"
import localFont from "next/font/local"
import SiteFooter from "@/components/SiteFooter"
import "./globals.css"

const geistSans = localFont({
  src: "../public/fonts/JosefinSans-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  display: "swap",
})

const geistMono = localFont({
  src: "../public/fonts/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col">
          <main className="flex-1">{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  )
}
